import axios from 'axios';
import React from 'react';
import useSWR from 'swr';
import Image from 'next/image';
// import coursesData from '../utils/CoursesData'
import Course from './Course';
import {useCart} from './context/cart-context'
import Head from 'next/head';


const Courses = ({count, setLoading, setLength}) => {
    const [courses, setCourses] = React.useState([])
    const {getCartLength, filterCourse} = useCart();
    const handleAddToCart = (courseId) => {
        axios.post(`/api/cart/${courseId}`).then(res => {
            alert(res.data.message)
        })
        getCartLength()
    }
    React.useEffect(() => { 
        setLoading(true)
        axios.put(`/api/courses/${count}`).then(({data}) => {
            setCourses(data.message)
            setLength(data.length)
            setLoading(false)
        })
    }, [count])
    return (
        <div className='lg:px-32 px-4 '>
            <Head>
                <title>Courses</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/monogram.ico" />
            </Head>
            {
                courses?.map(info => (
                    <div key={info.cid} className="card lg:card-side shadow-xl mb-12">
                        {/* <figure><Image className='' src={info.cimage} alt="Album" /></figure> */}
                        <figure><img src={`/uploads/images/${info.cimage}`} alt="" className='object-cover w-[30rem] h-[25rem]' /></figure>
                        <div className="card-body bg-[#e2f5ff] lg:w-16">
                            <h2 className="text-4xl font-bold text-[#0070f4]">{info.cname}</h2>
                            <div>
                                <p className='font-semibold mt-6'>{info.cdesc}</p>
                            </div>
                            <div>
                                <p className='font-semibold mt-6 text-xl'>Price: $ {info.cprice}</p>
                            </div>
                            
                            {/* <div className='flex lg:flex-row flex-col'>
                                <div className='flex items-center gap-2'>
                                    <p className='font-semibold text-xl'>{rating}</p>
                                    <div className="divider lg:divider-horizontal font-bold"></div>
                                </div>
                                <div className='flex items-center gap-2 lg:w-32 w-36'>
                                    <p className='font-semibold text-xl'>{info.cprice}$</p>
                                    <Image src={priceIcon} alt="Album" width="25px" height="25px" />
                                </div>
                            </div> */}

                            <div className="card-actions justify-end">
                                <button onClick={() => handleAddToCart(info.cid)} className="btn bg-[#0070f4] border-none outline-none text-white hover:bg-[#0754ac]" >Add To Cart</button>
                            </div>
                        </div>
                    </div>
                ))
            }
            {/* {
                data?.message.map(course => <Course
                    key={course.cid}
                    course={course}
                />)
            } */}

        </div>

    );
};

export default Courses;

