import React from 'react';
import Head from 'next/head'
import logo from '../public/images/logo.png'
// import logo from '../public'

const HeadTag = ({title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href={logo} /> */}
                <link rel="shortcut icon" href='/master admin/icon/Supervisor Solutions Logo for header.png' type="image/x-icon" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
        </>
    );
};

export default HeadTag;