import image1 from '../public/images/image1.png'
import image2 from '../public/images/image2.png'
import image3 from '../public/images/image3.png'
import image4 from '../public/images/image4.png'
import difficulty from '../public/images/difficulty.png'
import moduleIcon1 from '../public/images/moduleIcon.png'
import studentIcon from '../public/images/studentIcon.png'
import priceIcon from '../public/images/priceIcon.png'
import bookModuleIcon from '../public/images/Book modules.png'

const coursesData = [
    {
        id: '1',
        image: image1,
        instructor: "Thomas Smith",
        title: "Federal Motor Carrier Safety Administration (FMCSA) Supervisor Training",
        description1: "This Drugs and Alcohol Signs and Symptoms training program covers all the necessary requirements to ensure your DOT compliance for FMCSA. Covering CDL Holders and Carriers under regulation 49 CFR, part 382, your supervisor training program will last a total of two hours. The first hour will cover the drugs element and the second will encompass alcohol signs and symptoms.",
        description2: "With the 'certified' logo, Current Consulting Group certifies that, to the best of our knowledge, these courses meet DOT training requirements.  These courses have not been officially reviewed and approved by the DOT unless required by the DOT, or unless evaluated as part of a customer's DOT audit.  The DOT does not endorse courses, and has no affiliation with Current Consulting Group nor its partners and agents.  When viewed through the CCG web-based LMS (this site), these courses meet the DOT time and content requirements as published in the Federal Register.  CCG has no ability to ensure that trainees actually view the course materials while they are being displayed, nor are the actual users of the system completing the exams.  An employer's compliance with Federal Regulations is the sole responsibility of the employer, and an employee's understanding and use of the content presented is the sole responsibility of the employer.  By using this site you agree that any disputes will be resolved via arbitration on an individual basis and not as a group, and that any damages are limited to the monetary expenditure of the user for this training.",
        mode: "Difficulty",
        modeIcon: difficulty,
        module: "25 Module",
        moduleIcon1: moduleIcon1,
        student: "19k Student",
        studentIcon: studentIcon,
        rating: "Rating ⭐⭐⭐⭐⭐",
        price: "30",
        priceIcon: priceIcon,
        bookModuleIcon: bookModuleIcon,
        moduleText1: "1. Demo Course Introduction Module",
        moduleText2: "2. Demo Course DOT Regulations Module",
        moduleText3: "3. Demo Course Quiz",
        moduleText4: "4. Demo Forms Packet",

    },
    {
        id: '2',
        image: image2,
        instructor: "Thomas Smith",
        title: "Unrivaled, Detailed Training",
        description1: "Choose Supervisor Solutions as your provider to receive outstanding service and content. Each of our training programs has been carefully written to ensure the content covers the necessary regulations. We have been considerate to who is covered too, giving you the peace of mind that you have ensured full compliance for your DOT mode.",
        description2: "With the 'certified' logo, Current Consulting Group certifies that, to the best of our knowledge, these courses meet DOT training requirements.  These courses have not been officially reviewed and approved by the DOT unless required by the DOT, or unless evaluated as part of a customer's DOT audit.  The DOT does not endorse courses, and has no affiliation with Current Consulting Group nor its partners and agents.  When viewed through the CCG web-based LMS (this site), these courses meet the DOT time and content requirements as published in the Federal Register.  CCG has no ability to ensure that trainees actually view the course materials while they are being displayed, nor are the actual users of the system completing the exams.  An employer's compliance with Federal Regulations is the sole responsibility of the employer, and an employee's understanding and use of the content presented is the sole responsibility of the employer.  By using this site you agree that any disputes will be resolved via arbitration on an individual basis and not as a group, and that any damages are limited to the monetary expenditure of the user for this training.",
        mode: "Difficulty",
        modeIcon: difficulty,
        module: "10 Module",
        moduleIcon1: moduleIcon1,
        student: "20k Student",
        studentIcon: studentIcon,
        rating: "Rating ⭐⭐⭐⭐⭐",
        price: "30",
        priceIcon: priceIcon,
        bookModuleIcon: bookModuleIcon,
        moduleText1: "1. Demo Course Introduction Module",
        moduleText2: "2. Demo Course DOT Regulations Module",
        moduleText3: "3. Demo Course Quiz",
        moduleText4: "4. Demo Forms Packet",
    },
    {
        id: '3',
        image: image3,
        instructor: "Thomas Smith",
        title: "DOT Mode Training Across the US",
        description1: "Are you concerned that you will not be able to access this first-class material due to your location? We are delighted to offer our training online across the United States of America, covering all 50 states. No matter where you are in the US, we will support you and your business, ensuring that we can help you stay compliant with the required training for your DOT safety sensitive modes.",
        description2: "With the 'certified' logo, Current Consulting Group certifies that, to the best of our knowledge, these courses meet DOT training requirements.  These courses have not been officially reviewed and approved by the DOT unless required by the DOT, or unless evaluated as part of a customer's DOT audit.  The DOT does not endorse courses, and has no affiliation with Current Consulting Group nor its partners and agents.  When viewed through the CCG web-based LMS (this site), these courses meet the DOT time and content requirements as published in the Federal Register.  CCG has no ability to ensure that trainees actually view the course materials while they are being displayed, nor are the actual users of the system completing the exams.  An employer's compliance with Federal Regulations is the sole responsibility of the employer, and an employee's understanding and use of the content presented is the sole responsibility of the employer.  By using this site you agree that any disputes will be resolved via arbitration on an individual basis and not as a group, and that any damages are limited to the monetary expenditure of the user for this training.",
        mode: "Difficulty",
        modeIcon: difficulty,
        module: "15 Module",
        moduleIcon1: moduleIcon1,
        student: "20k Student",
        studentIcon: studentIcon,
        rating: "Rating ⭐⭐⭐⭐⭐",
        price: "30",
        priceIcon: priceIcon,
        bookModuleIcon: bookModuleIcon,
        moduleText1: "1. Demo Course Introduction Module",
        moduleText2: "2. Demo Course DOT Regulations Module",
        moduleText3: "3. Demo Course Quiz",
        moduleText4: "4. Demo Forms Packet",
    },
    {
        id: '4',
        image: image4,
        instructor: "Thomas Smith",
        title: "Drug-Free Workplace Training",
        description1: "Are you in need of supervisor training to ensure your business is drug-free compliant? Offering a comprehensive program including relevant content to comply with regulations, our easy-to-follow course will ensure your supervisors are completely trained to the appropriate level. ",
        description2: "With the 'certified' logo, Current Consulting Group certifies that, to the best of our knowledge, these courses meet DOT training requirements.  These courses have not been officially reviewed and approved by the DOT unless required by the DOT, or unless evaluated as part of a customer's DOT audit.  The DOT does not endorse courses, and has no affiliation with Current Consulting Group nor its partners and agents.  When viewed through the CCG web-based LMS (this site), these courses meet the DOT time and content requirements as published in the Federal Register.  CCG has no ability to ensure that trainees actually view the course materials while they are being displayed, nor are the actual users of the system completing the exams.  An employer's compliance with Federal Regulations is the sole responsibility of the employer, and an employee's understanding and use of the content presented is the sole responsibility of the employer.  By using this site you agree that any disputes will be resolved via arbitration on an individual basis and not as a group, and that any damages are limited to the monetary expenditure of the user for this training.",
        mode: "Difficulty",
        modeIcon: difficulty,
        module: "5 Module",
        moduleIcon1: moduleIcon1,
        student: "16k Student",
        studentIcon: studentIcon,
        rating: "Rating ⭐⭐⭐⭐⭐",
        price: "30",
        priceIcon: priceIcon,
        bookModuleIcon: bookModuleIcon,
        moduleText1: "1. Demo Course Introduction Module",
        moduleText2: "2. Demo Course DOT Regulations Module",
        moduleText3: "3. Demo Course Quiz",
        moduleText4: "4. Demo Forms Packet",
    },
]

export default coursesData