// import dynamic from "next/dynamic";

// const PDFViewer = dynamic(() => import("../components/PdfViwer"), {
//   ssr: false
// });

// export default function PDF() {
//   return <PDFViewer />;
// }
import CertificateGenerator from "../components/CertificateGenerator";
import useCart from "../components/context/cart-context/useCart";
import { Marks } from "../components/CompleteQuiz";
import {useRouter} from 'next/router'
import {useEffect} from 'react'
import Head from "next/head";

function App() {
  const {marks, ccode} = useRouter().query
  const history = useRouter()
  useEffect(() => {  
    if(!Marks && !marks) history.push("/")
  }, [])
  return (
    <div className="container px-[4%]">
      <Head>
          <title>Certificate</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/monogram.ico" />
      </Head>
      <h1 className="text-center text-xl text-green-500 font-semibold mt-2">♕ Congratulations! <span className="">You are certified.</span></h1>

      {/* certificate generator component */}
      <CertificateGenerator />
    </div>
  );
}

export default App;
