import React, {useEffect, useState, useContext} from 'react';
import Image from 'next/image';
import Aos from 'aos';
import 'aos/dist/aos.css';
import footLogo from '../public/images/footLogo.png'
import logo1 from '../public/images/logo1.png'
import logo from '../public/images/logo.png';
import Link from 'next/link'
import Head from 'next/head';

import circleImg from '../public/images/circleImg.png';
import circleImg1 from '../public/images/circleImage.png';
import axios from 'axios';
import {context} from '../pages/_app'
import { useRouter } from 'next/router';
import useSWR from 'swr';

const fetcher = async () => {
    const {data} = await axios.get("/api/hello")
    return data
}

const login = () => {
    const history = useRouter()
    const {data} = useSWR("/api/hello", fetcher)
    if(data?.token || data?.companyToken) history.push("/")
    useEffect(() => {
        Aos.init({duration: 2000});
    })
    const [formData, setFormData] = useState({
        email: "", password: ""
    })
    const changeValue = e => {
        setFormData({
            ...formData, [e.target.name]: e.target.value
        })
    }
    const submit = async e => {
        e.preventDefault()
        const {data} = await axios.post("/api/companyLogin", formData)
        if(data.status === 200) history.reload("/")
        else alert(data.message)
    }
    return (
        <div>
            {/* heading start */}
            <Head>
                <title>Supervisor solutions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/monogram.ico" />
            </Head>
                
                    <div className=" py-5 mx-auto">
                    <div className="navbar bg-base-100 max-w-7xl mx-auto flex items-center justify-between">
                            <div className="navbar-start cursor-pointer">
                                <Link href="/" >
                                    <Image
                                        src={logo}
                                        alt="logo"
                                        width="235"
                                        height="65px"
                                    />
                                </Link>
                            </div>
                    </div>
                  {/* heading */}
                </div>
        {/* circle */}
                {/* <div className="flex ">
                        <div className="" data-aos="fade-down-right">
                            <Image src={circleImg} alt="images" width="150" height="160" />
                        </div> */}
                        
                    <div className='max-w-7xl mx-auto  min-h-screen flex justify-center items-center'>
                    
                
                        <div className="lg:card lg:w-2/4 h-full bg-[#e2f5ff] shadow-xl pb-20">
                            <div>
                                <h2 className='text-center text-3xl bg-[#1F497B] text-white py-6'>Company Login</h2>
                                <div className='w-1/5 mx-auto flex flex-col items-center'>
                                    <Image
                                        src={footLogo}
                                        alt="logo"

                                    />
                                    <Image
                                        src={logo1}
                                        alt="logo"
                                    />
                                </div>
                            </div>
                            <div className='lg:px-0 px-2 '>
                                <div className='flex items-center justify-center'>
                                    <h2 className='pr-2 text-[#1F497B] font-semibold'>Email</h2>
                                    <input onChange={changeValue} required type="email" name='email' placeholder="Type here" className="input input-bordered w-full max-w-xs" />
                                </div>
                                <div className='flex items-center justify-center mt-8'>
                                    <h2 className='pr-2 text-[#1F497B] font-semibold'>Password</h2>
                                    <input onChange={changeValue} required type="password" name='password' placeholder="Type here" className="input input-bordered w-full max-w-xs" />
                                </div>

                                {/* <div className='flex items-center justify-center mt-14'>
                                    <h2 className='pr-2 text-[#1F497B] font-semibold'>Role</h2>
                                    <select className="select select-bordered select-sm w-full max-w-xs">
                                        <option disabled selected>Select Field</option>
                                        <option>Company</option>
                                        <option>Student</option>
                                    </select>
                                </div> */}
                                <div className='my-12 flex justify-center'>
                                    <button onClick={submit} className="btn btn-sm bg-[#1F497B] border-none  drop-shadow-lg ">Login</button>
                                </div>
                                    {/* <div className='px-8   cursor-pointer hover:text-red-500'>
                                        <Link href="#" className="">Forget Password</Link>
                                    </div> */}
                                <div className='mt-12  flex justify-around items-center lg:pb-0 pb-4 '>
                                    {/* <div className='cursor-pointer hover:text-red-500'>
                                        <Link href="/forgot-password" className='font-semibold cursor-pointer hover:text-red-500 drop-shadow-lg'>Forgot Password?</Link>
                                    </div> */}
                                    <div className='cursor-pointer hover:text-red-500'>
                                        <Link href="#" className='font-semibold cursor-pointer hover:text-red-500 drop-shadow-lg'>Dont have an account?</Link>
                                    </div>
                                    <Link href={`/signup`}>
                                        <button className="p-2 shadow-lg rounded-lg bg-base-100 text-[#1F497B] border-none font-semibold">Create an Account</button>
                                    </Link>
                                </div>
                            </div>
                        </div>
                        <div className="" data-aos="fade-left">
                            <Image src={circleImg} alt="images" width="150" height="160" />
                        </div>
                        
                    </div>
                    
                {/* </div> */}
                <div className="mb-8"></div>
    </div>
    );
};

export default login;