import React from 'react';
import NavbarForAll from '../components/NavbarForAll'
import Footer from '../components/Footer'
const content01 = () => {
    return (
        <>
         <NavbarForAll />
        <div className="bg-gradient-to-r from-[#eceff3] to-[#C0DDFF] p-4 pt-28">
            <dev>
                <h1 className="text-center text-red-500 text-3xl   font-semibold ">Modal Responsibilities for Training</h1>
            </dev>
            <dev className="text-left my-2 mx-2">
                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">Federal Motor Carrier Safety Administration (FMCSA)</h2>
                <p className="  font-semibold  my-2"> “Each employer shall ensure that all persons designated to supervise drivers receive at least 60 minutes of training on alcohol misuse and receive at least 60 additional minutes of training on controlled substance drug use. The training shall include the physical, behavioral, speech, and performance indicators of probable alcohol misuse and use of controlled substances. Recurrent training is not required.”(49 CFR Part 382.603). The Federal Motor Carrier Safety Administration (FMCSA) provides safety measures and regulation to the industry, for trucking and other safety sensitive positions. The FMCSA is part of the Department of Transportation (DOT), required drug and alcohol testing program is a mandatory part of FMCSA rules and regulations. The FMCSA requires Signs and Symptoms Training of drugs and alcohol which is mandatory for all supervisors who manage/oversee one or more employees. FMCSA Supervisor Training is over 2 hours, as mandated by federal law. Reoccurring training is not needed on an annual basis, it’s only required once.</p>
                {/* ----------- */}
                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">Federal Aviation Administration (FAA)</h2>
                <p className="  font-semibold  my-2">“The employer’s supervisory personnel who will determine when an employee is subject to testing based on reasonable cause shall receive specific training on specific contemporaneous physical, behavioral, and performance indicators of probable drug use. The employer shall ensure that supervisors who will make reasonable cause determinations receive at least 60 minutes of initial training. The employer shall implement a reasonable recurrent training program for supervisory personnel making reasonable cause determinations during subsequent years.” 
(14 CFR Part 121 Appendix I, Sec. VIII B)“Each employer shall ensure that ensure that persons designated to determine whether reasonable suspicion exists to require a covered employee to undergo alcohol testing. Supervisor is required to receive at least 60 minutes of training on the physical, behavioral, speech and performance indicators of probable alcohol misuse.” (14 CFR Part 121 Appendix J, Sec. VI B) The Federal Aviation Administration (FAA) provides safety measures and regulation to the industry, for airfare and other safety sensitive positions. The FAA is part of the Department of Transportation (DOT), required drug and alcohol testing program is a mandatory part of FAA rules and regulations. The FAA requires Signs and Symptoms Training of drugs and alcohol which is mandatory for all supervisors who manage/oversee one or more employees. FAA Supervisor Training is over 2 hours; reoccurring training is needed on a continuing basis as mandated by federal law.</p>
                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">Federal Railroad Administration (FRA)</h2>
                <p className="  font-semibold  my-2">“Each supervisor responsible for covered employees (except a working supervisor within the definition of co-worker under the part) must be trained in the signs and symptoms of alcohol and drug influence, intoxication and misuse consistent with a program of instruction to be made available for inspection upon demand by the FRA. Such a program shall, at a minimum, provide information concerning the acute behavioral and apparent physiological effects of alcohol and the major drug groups on the controlled substances list. The program must also provide training on the qualifying criteria for post-accident testing and the role of the supervisor in post-accident collections. The duration of such training may not be less than 3 hours” as mandated by federal law.” (49 CFR Part 219.11(g)) The Federal Railroad Administration (FRA) provides safety measures and regulation to the industry, for railway safety sensitive positions. The FRA is part of the Department of Transportation (DOT), required drug and alcohol testing program is a mandatory part of FRA rules and regulations. The FRA requires Signs and Symptoms Training of drugs and alcohol which is mandatory for all supervisors who manage/oversee one or more employees. </p>

                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">Federal Transit Administration (FTA)</h2>
                <p className="  font-semibold  my-2">“Supervisors and/or other company authorized by the employer to make reasonable suspicion determinations shall receive at least 60 minutes on the physical, behavioral, and performance indicators of probable drug use and at least 60 minutes of training on the physical, behavioral, speech and performance indicators of probable alcohol misuse.” (49 CFR Part 655.14(b) (2)) The Federal Transit Administration (FTA) provides safety measures and regulation to the industry, for public transit systems, including buses, light rail, subways, trolleys, commuter rail, ferries and other safety sensitive positions. The FTA is part of the Department of Transportation (DOT), required drug and alcohol testing program is a mandatory part of FTA rules and regulations. The FTA requires Signs and Symptoms Training of drugs and alcohol which is mandatory for all supervisors who manage/oversee one or more employees. </p>

                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">FTA Supervisor Training</h2>
                <p className="  font-semibold  my-2">“Training under each EAP for supervisory personnel who will determine whether an employee must be drug tested based on reasonable cause must include one 60-minute period of training on the specific, contemporaneous physical, behavioral, and performance indicators of probable drug use.” (49 CFR Part 199.113(c)) “Each operator shall ensure that persons designated to determine whether reasonable suspicion exists to require a covered employee to undergo alcohol testing under 199.255(b) receive at least 60 minutes of training on the physical, behavioral, speech, and performance indicators of probable alcohol misuse.” (49 CFR Part 199.241) Pipeline and Hazardous Materials Safety Administration (PHMSA) is part of the Department of Transportation (DOT) and provides safety measures and regulation to the industry, for pipeline safety sensitive positions. The PHMSA requires under federal law, Signs and Symptoms Training of drugs and alcohol which is mandatory for all supervisors who manage/oversee one or more employees. PHMSA Supervisor Training is over 2 hours, as mandated by federal law. </p>
                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">Pipeline and Hazardous Material Safety Administration (PHMSA)</h2>
                <p className="  font-semibold  my-2">Supervisors must receive two hours of training, one on alcohol and one on drugs. This training must assist the supervisor to make reasonable suspicion determinations impairment while on duty. The observations must be contemporaneous and specific and based on the physical, behavioral, and performance indicators of probable alcohol use.</p>

               
                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">United States Coast Guard (USCG)</h2>
                <p className="  font-semibold  my-2">Supervisors must receive two hours of training, one on alcohol and one on drugs. This training must assist the supervisor to make reasonable suspicion determinations impairment while on duty. The observations must be contemporaneous and specific and based on the physical, behavioral, and performance indicators of probable alcohol use.</p>

                <h2 className="text-left text-[#06356C] text-xl  font-semibold ">Federal Motor Carrier Safety Administration (FMCSA)</h2>
                <p className="  font-semibold  my-2">“An Employee Assistance Program (EAP) training program must be conducted for the employer’s crewmembers and supervisory personnel. The training program must include at least the following elements: the effects and consequences of drug and alcohol use on personal health, safety, and work environment; the manifestations and behavioral cures that may indicate drug and alcohol use and abuse; and documentation of training given to crewmembers and employer’s supervisory personnel. Supervisory personnel must receive at least 60 minutes of training for drugs and alcohol.” (49 CFR Part 16.401(b)) United States Coast Guard (USCG) is part of the Department of Transportation (DOT) and provides safety measures and regulation to the industry, for USCG maritime safety sensitive positions. The USCG requires under federal law, Signs and Symptoms Training of drugs and alcohol which is mandatory for all supervisors who manage/oversee one or more employees. USCG Supervisor Training is over 2 hours. </p>

            </dev>
        </div>
        <Footer />
        </>
    );
};

export default content01;