import React, {useState} from 'react';
import Image from 'next/image'
import UseSigUp from '../components/UseSigUp';
import ComSigUp from '../components/ComSigUp';
import Head from 'next/head'
import NavbarForAll from '../components/NavbarForAll'
const Signup = () => {
    const [comShow, setComShow] = useState(false);
    return (

        <div>
            <Head>
                <title>Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/monogram.ico" />
            </Head>

            {/* <NavbarForAll /> */}
            {
                comShow ?   <ComSigUp comShow={comShow} setComShow={setComShow}/> : <UseSigUp comShow={comShow} setComShow={setComShow} />
            }
           
           
        </div>
    );
};

export default Signup;